export default {
  FIND_DATES_TO_IGNORE_REQUEST: "FIND_DATES_TO_IGNORE_REQUEST",
  FIND_DATES_TO_IGNORE_SUCCESSFUL: "FIND_DATES_TO_IGNORE_SUCCESSFUL",
  FIND_DATES_TO_IGNORE_FAILED: "FIND_DATES_TO_IGNORE_FAILED"
};
