export default {
  SET_FORM_TO_DEFAULT: "SET_FORM_TO_DEFAULT",
  RESET_DEFAULT: "RESET_DEFAULT",
  ADD_LISTING_REQUEST: "ADD_LISTING_REQUEST",
  ADD_LISTING_SUCCESSFUL: "ADD_LISTING_SUCCESSFUL",
  ADD_LISTING_FAILED: "ADD_LISTING_FAILED",

  UPDATE_LISTING_REQUEST: "UPDATE_LISTING_REQUEST",
  UPDATE_LISTING_SUCCESSFUL: "UPDATE_LISTING_SUCCESSFUL",
  UPDATE_LISTING_FAILED: "UPDATE_LISTING_FAILED",

  DELETE_LISTING_REQUEST: "DELETE_LISTING_REQUEST",
  DELETE_LISTING_SUCCESSFUL: "DELETE_LISTING_SUCCESSFUL",
  DELETE_LISTING_FAILED: "DELETE_LISTING_FAILED",

  SNOOZE_LISTING_REQUEST: "SNOOZE_LISTING_REQUEST",
  SNOOZE_LISTING_SUCCESSFUL: "SNOOZE_LISTING_SUCCESSFUL",
  SNOOZE_LISTING_FAILED: "SNOOZE_LISTING_FAILED",

  FIND_LISTINGS_REQUEST: "FIND_LISTINGS_REQUEST",
  FIND_LISTINGS_SUCCESSFUL: "FIND_LISTINGS_SUCCESSFUL",
  FIND_LISTINGS_FAILED: "FIND_LISTINGS_FAILED",

  FIND_ONE_LISTING_REQUEST: "FIND_ONE_LISTING_REQUEST",
  FIND_ONE_LISTING_SUCCESSFUL: "FIND_ONE_LISTING_SUCCESSFUL",
  FIND_ONE_LISTING_FAILED: "FIND_ONE_LISTING_FAILED",

  FIND_PUBLIC_LISTINGS_REQUEST: "FIND_PUBLIC_LISTINGS_REQUEST",
  FIND_PUBLIC_LISTINGS_SUCCESSFUL: "FIND_PUBLIC_LISTINGS_SUCCESSFUL",
  FIND_PUBLIC_LISTINGS_FAILED: "FIND_PUBLIC_LISTINGS_FAILED",

  UPDATE_LISTING_FORM: "UPDATE_LISTING_FORM",
  CLEAR_FORM: "CLEAR_FORM",
  BACK_UP_FORM: "BACK_UP_FORM",

  MAKE_RATING_REQUEST: "MAKE_RATING_REQUEST"
};
